#include "ps_shader.h"

#define PS_SHADER_LOADING_PUSH_CONSTANTS \
"struct PushConstantData {\n" \
"   float windowWidth;\n" \
"   float windowHeight;\n" \
"   float progress;\n" \
"   float padding;\n" \
"};\n" \
"layout(push_constant) uniform PushConstants {\n" \
"   PushConstantData data;\n" \
"} pushConstants;\n"

const char* psShader_LoadingVertex =
    "#version 450\n"
    "#pragma shader_stage(vertex)\n"
    "layout(location = 0) out vec2 outUV;\n"
    PS_SHADER_LOADING_PUSH_CONSTANTS
    "const vec2 positions[6] = vec2[](\n"
    "    vec2(0.0, 0.0),\n"
    "    vec2(0.0, 1.0),\n"
    "    vec2(1.0, 1.0),\n"
    "    vec2(0.0, 0.0),\n"
    "    vec2(1.0, 1.0),\n"
    "    vec2(1.0, 0.0)\n"
    ");\n"
    "void main() {\n"
    "    vec2 pos = positions[gl_VertexIndex];\n"
    "    // adjust the rect to be a square quad in the center of the screen\n"
    "    outUV = pos;\n"
    "    pos = pos * 2.0 - 1.0;\n"
    "    float aspectRatio = pushConstants.data.windowWidth / pushConstants.data.windowHeight;\n"
    "    if (aspectRatio > 1.0) {\n"
    "        pos.x /= aspectRatio;\n"
    "    } else {\n"
    "        pos.y *= aspectRatio;\n"
    "    }\n"   
    "    pos *= 1.4;\n"
    "    gl_Position = vec4(pos, 0.0, 1.0);\n"
    "}\n";

const char* psShader_LoadingFragment =
    "#version 450\n"
    "#pragma shader_stage(fragment)\n"
    "precision highp float;\n"
    "\n"
    "layout(location = 0) in vec2 inUV;\n"
    "\n"
    PS_SHADER_LOADING_PUSH_CONSTANTS
    "\n"
    "layout(location = 0) out vec4 outColor;\n"
    "\n"
    PS_SHADER_UTILS
    "\n"
    "void main() {\n"
    "    vec2 uv = (inUV * 2.0 - 1.0);\n"
    "\n"
    "    vec4 backgroundColor = vec4(0.0);\n"
    "    vec4 barBackgroundColor = vec4(180.0/255.0, 141.0/255.0, 209.0/255.0, 1.0);\n"
    "    vec4 barForegroundColor = vec4(79.0/255.0, 45.0/255.0, 95.0/255.0, 1.0);\n"
    "    vec4 trackBackgroundColor = vec4(130.0/255.0, 88.0/255.0, 150.0/255.0, 1.0);\n"
    "    vec4 borderColor = vec4(60.0/255.0, 40.0/255.0, 70.0/255.0, 1.0);\n"
    "\n"
    "    float barWidth = 1.0;\n"
    "    float barHeight = 0.1;\n"
    "    float borderThickness = 0.015;\n"
    "\n"
    "    vec2 capsuleStart = vec2(-barWidth / 2.0, 0.0);\n"
    "    vec2 capsuleEnd = vec2(barWidth / 2.0, 0.0);\n"
    "    vec2 capsuleProgressEnd = vec2(-barWidth / 2.0 + barWidth * pushConstants.data.progress, 0.0);\n"
    "\n"
    "    float capsuleOuter = sdCapsule(uv, capsuleStart, capsuleEnd, barHeight);\n"
    "    float capsuleInner = sdCapsule(uv, capsuleStart, capsuleEnd, barHeight - borderThickness);\n"
    "    float capsuleTrack = sdCapsule(uv, capsuleStart, capsuleEnd, barHeight - 2.0 * borderThickness);\n"
    "    float capsuleProgress = sdCapsule(uv, capsuleStart, capsuleProgressEnd, barHeight - 2.0 * borderThickness);\n"
    "    float capsuleProgressInner = sdCapsule(uv, capsuleStart, capsuleProgressEnd, barHeight - 3.0 * borderThickness);\n"
    "\n"
    "    vec4 finalColor = backgroundColor;\n"
    "\n"
    "    float aa = 1.5 / pushConstants.data.windowHeight;\n"
    "\n"
    "    float borderShape = max(capsuleOuter, -capsuleInner);\n"
    "    float progressBorderShape = max(capsuleProgress, -capsuleProgressInner);\n"
    "    finalColor = mix(finalColor, barBackgroundColor, smoothstep(-aa, aa, capsuleOuter));\n"
    "    finalColor = mix(finalColor, borderColor, smoothstep(aa, -aa, borderShape));\n"
    "    finalColor = mix(finalColor, trackBackgroundColor, smoothstep(-aa, aa, -capsuleTrack));\n"
    "    finalColor = mix(finalColor, barForegroundColor, smoothstep(-aa, aa, -capsuleProgress));\n"
    "    finalColor = mix(finalColor, borderColor, smoothstep(aa, -aa, progressBorderShape));\n"
    "\n"
    "    if (capsuleOuter >= 0.0) {\n"
    "        finalColor.a = 0.0;\n"
    "    }\n"    
    ""
    "\n"
    "    float contrast = 1.1;\n"
    "    finalColor.rgb = (finalColor.rgb - 0.5) * contrast + 0.5;\n"
    "\n"
    "    float noise = (random(gl_FragCoord.xy / 2.0) - 0.5) * 0.05;\n"
    "    finalColor.rgb += noise;\n"
    "    finalColor.rgb = clamp(finalColor.rgb, 0.0, 1.0);\n"
    "\n"
    "    outColor = finalColor;\n"
    "}\n";
