#include "ps_shader.h"

#define PS_SHADER_MAIN_MENU_PUSH_CONSTANTS "" \
"\n" \
"struct PushConstantsData {\n" \
"    float windowWidth;\n" \
"    float windowHeight;\n" \
"    float time;\n" \
"    float backgroundImageWidth;\n" \
"    float backgroundImageHeight;\n" \
"    float buttonImageWidth;\n" \
"    float buttonImageHeight;\n" \
"    float hoverScaleFactor;\n" \
"    float hoverOffsetY;\n" \
"    int hoveredButton; // 0: None, 1: New Game, 2: Continue, 3: Options, 4: Exit\n" \
"    int continueDisabled; // 0: Enabled, 1: Disabled\n" \
"};\n" \
"\n" \
"layout(push_constant) uniform PushConstants {\n" \
"    PushConstantsData data;\n" \
"} pushConstants;\n" \
"\n" \

const char* psShader_MainMenuVertex = ""
"#version 450\n"
"#pragma shader_stage(vertex)\n"
"layout(location = 0) out vec2 outUV;\n"
"const vec2 positions[6] = vec2[](\n"
"    vec2(-1.0, -1.0),\n"
"    vec2(-1.0,  1.0),\n"
"    vec2( 1.0,  1.0),\n"
"    vec2(-1.0, -1.0),\n"
"    vec2( 1.0,  1.0),\n"
"    vec2( 1.0, -1.0)\n"
");\n"
"const vec2 uvs[6] = vec2[](\n"
"    vec2(0.0, 1.0),\n"
"    vec2(0.0, 0.0),\n"
"    vec2(1.0, 0.0),\n"
"    vec2(0.0, 1.0),\n"
"    vec2(1.0, 0.0),\n"
"    vec2(1.0, 1.0)\n"
");\n"
"void main() {\n"
"    gl_Position = vec4(positions[gl_VertexIndex], 0.0, 1.0);\n"
"    outUV = uvs[gl_VertexIndex];\n"
"}\n";

const char* psShader_MainMenuFragment = ""
"#version 450\n"
"#pragma shader_stage(fragment)\n"
"layout(location = 0) in vec2 inUV;\n"
"layout(location = 0) out vec4 outColor;\n"
"\n"
"layout(set = 0, binding = 0) uniform sampler2D backgroundTexture;\n"
"layout(set = 0, binding = 1) uniform sampler2D newGameButtonTexture;\n"
"layout(set = 0, binding = 2) uniform sampler2D continueButtonTexture;\n"
"layout(set = 0, binding = 3) uniform sampler2D optionsButtonTexture;\n"
"layout(set = 0, binding = 4) uniform sampler2D exitButtonTexture;\n"
"layout(set = 0, binding = 5) uniform sampler2D mascotHopeTexture;\n"
"layout(set = 0, binding = 6) uniform sampler2D mascotCrushTexture;\n"
"layout(set = 0, binding = 7) uniform sampler2D mascotMonsterTexture;\n"
"layout(set = 0, binding = 8) uniform sampler2D mascotFriendTexture;\n"
"\n"
PS_SHADER_MAIN_MENU_PUSH_CONSTANTS
"\n"
"const float buttonHeightUV = 0.1;\n"
"const float buttonCenterYStart = 0.55;\n"
"const float buttonSpacingY = 0.12;\n"
"const float buttonCenterX = 0.5;\n"
"\n"
"const float mascotSizeUV = 0.15;\n"
"\n"
"vec4 sampleRect(vec2 uv, vec2 center, vec2 size, sampler2D tex) {\n"
"    vec2 halfSize = size * 0.5;\n"
"    vec2 minBound = center - halfSize;\n"
"    vec2 maxBound = center + halfSize;\n"
"\n"
"    if (uv.x >= minBound.x && uv.x <= maxBound.x && uv.y >= minBound.y && uv.y <= maxBound.y) {\n"
"        vec2 localUV = (uv - minBound) / size;\n"
"        return pow(texture(tex, localUV), vec4(1.3));\n"
"    }\n"
"    return vec4(0.0);\n"
"}\n"
"\n"
"void main() {\n"
"    vec2 flippedUV = vec2(inUV.x, 1.0 - inUV.y);\n"
"\n"
"    float screenAspect = pushConstants.data.windowWidth / pushConstants.data.windowHeight;\n"
"\n"
"    float bgTargetAspect = pushConstants.data.backgroundImageWidth / pushConstants.data.backgroundImageHeight;\n"
"    vec2 bgScale = vec2(1.0, 1.0);\n"
"    vec2 bgOffset = vec2(0.0, 0.0);\n"
"    if (screenAspect > bgTargetAspect) {\n"
"        bgScale.x = bgTargetAspect / screenAspect;\n"
"        bgOffset.x = (1.0 - bgScale.x) * 0.5;\n"
"    } else {\n"
"        bgScale.y = screenAspect / bgTargetAspect;\n"
"        bgOffset.y = (1.0 - bgScale.y) * 0.5;\n"
"    }\n"
"    vec2 backgroundUV = (flippedUV - bgOffset) / bgScale;\n"
"    vec4 bgColor = vec4(0.0, 0.0, 0.0, 0.0);\n"
"    if (backgroundUV.x >= 0.0 && backgroundUV.x <= 1.0 && backgroundUV.y >= 0.0 && backgroundUV.y <= 1.0) {\n"
"        bgColor = texture(backgroundTexture, backgroundUV);\n"
"    }\n"
"\n"
"    vec4 finalColor = bgColor;\n"
"\n"
"    float time = pushConstants.data.time;\n"
"\n"
"    float mascotAspect = 1.0; // Assuming square mascots\n"
"    float mascotWidthUV = mascotSizeUV * mascotAspect * (pushConstants.data.windowHeight / pushConstants.data.windowWidth);\n"
"    vec2 mascotDrawSize = vec2(mascotWidthUV, mascotSizeUV);\n"
"\n"
"    vec2 hopePos = vec2(0.15, 0.8) + vec2(cos(time * 0.8 + 1.0) * 0.01, sin(time * 1.1 + 2.0) * 0.015);\n"
"    vec2 crushPos = vec2(0.85, 0.8) + vec2(cos(time * 0.9 - 0.5) * 0.015, sin(time * 1.0 - 1.0) * 0.01);\n"
"    vec2 monsterPos = vec2(0.1, 0.2) + vec2(cos(time * 1.2 + 3.0) * 0.01, sin(time * 0.7 + 0.5) * 0.015);\n"
"    vec2 friendPos = vec2(0.86, 0.3) + vec2(cos(time * 1.0 + 0.2) * 0.012, sin(time * 0.9 + 1.5) * 0.01);\n"
"\n"
"    vec4 mascotColor = vec4(0.0);\n"
"    mascotColor = sampleRect(flippedUV, hopePos, mascotDrawSize, mascotHopeTexture);\n"
"    if (mascotColor.a > 0.0) { finalColor = mix(finalColor, mascotColor, mascotColor.a); }\n"
"\n"
"    mascotColor = sampleRect(flippedUV, crushPos, mascotDrawSize, mascotCrushTexture);\n"
"    if (mascotColor.a > 0.0) { finalColor = mix(finalColor, mascotColor, mascotColor.a); }\n"
"\n"
"    mascotColor = sampleRect(flippedUV, monsterPos, mascotDrawSize, mascotMonsterTexture);\n"
"    if (mascotColor.a > 0.0) { finalColor = mix(finalColor, mascotColor, mascotColor.a); }\n"
"\n"
"    mascotColor = sampleRect(flippedUV, friendPos, mascotDrawSize, mascotFriendTexture);\n"
"    if (mascotColor.a > 0.0) { finalColor = mix(finalColor, mascotColor, mascotColor.a); }\n"
"\n"
"    float buttonImageAspect = pushConstants.data.buttonImageWidth / pushConstants.data.buttonImageHeight;\n"
"    float windowAspect = pushConstants.data.windowWidth / pushConstants.data.windowHeight;\n"
"    float buttonWidthUV = buttonHeightUV * buttonImageAspect / windowAspect;\n"
"    vec2 correctedButtonSize = vec2(buttonWidthUV, buttonHeightUV);\n"
"\n"
"   float buttonScale[4];\n"
"    buttonScale[0] = 1.0;\n"
"    buttonScale[1] = 1.0;\n"
"    buttonScale[2] = 1.0;\n"
"    buttonScale[3] = 1.0;\n"
"\n"
"    vec2 buttonPositions[4];\n"
"    buttonPositions[0] = vec2(buttonCenterX, buttonCenterYStart + buttonSpacingY * 0.0);\n"
"    buttonPositions[1] = vec2(buttonCenterX, buttonCenterYStart + buttonSpacingY * 1.0);\n"
"    buttonPositions[2] = vec2(buttonCenterX, buttonCenterYStart + buttonSpacingY * 2.0);\n"
"    buttonPositions[3] = vec2(buttonCenterX, buttonCenterYStart + buttonSpacingY * 3.0);\n"
"\n"
"    if (pushConstants.data.hoveredButton > 0 && pushConstants.data.hoveredButton <= 4) {\n"
"        int hoveredButton = pushConstants.data.hoveredButton - 1;\n"
"        buttonScale[hoveredButton] *= pushConstants.data.hoverScaleFactor;\n"
"        buttonPositions[hoveredButton].y += pushConstants.data.hoverOffsetY;\n"
"    }\n"
"\n"
"    vec4 btnColor = vec4(0.0);\n"
"\n"
"    btnColor = sampleRect(flippedUV, buttonPositions[0], correctedButtonSize * buttonScale[0], newGameButtonTexture);\n"
"    if (btnColor.a > 0.0) { finalColor = mix(finalColor, btnColor, btnColor.a); }\n"
"\n"
"    btnColor = sampleRect(flippedUV, buttonPositions[1], correctedButtonSize * buttonScale[1], continueButtonTexture);\n"
"    if (btnColor.a > 0.0) { finalColor = mix(finalColor, btnColor, btnColor.a * (pushConstants.data.continueDisabled == 1 ? 0.5 : 1.0)); }\n"
"\n"
"    btnColor = sampleRect(flippedUV, buttonPositions[2], correctedButtonSize * buttonScale[2], optionsButtonTexture);\n"
"    if (btnColor.a > 0.0) { finalColor = mix(finalColor, btnColor, btnColor.a); }\n"
"\n"
"    btnColor = sampleRect(flippedUV, buttonPositions[3], correctedButtonSize * buttonScale[3], exitButtonTexture);\n"
"    if (btnColor.a > 0.0) { finalColor = mix(finalColor, btnColor, btnColor.a); }\n"
"\n"
"    outColor = finalColor;\n"
"}\n";
