#include "ps_shader.h"

#define PS_SHADER_MAIN_MENU_PUSH_CONSTANTS "" \
"\n" \
"struct PushConstantsData {\n" \
"    float windowWidth;\n" \
"    float windowHeight;\n" \
"    float time;\n" \
"    float backgroundImageWidth;\n" \
"    float backgroundImageHeight;\n" \
"    float buttonImageWidth;\n" \
"    float buttonImageHeight;\n" \
"};\n" \
"\n" \
"layout(push_constant) uniform PushConstants {\n" \
"    PushConstantsData data;\n" \
"} pushConstants;\n" \
"\n" \

const char* psShader_MainMenuVertex = ""
"#version 450\n"
"#pragma shader_stage(vertex)\n"
"layout(location = 0) out vec2 outUV;\n"
"const vec2 positions[6] = vec2[](\n"
"    vec2(-1.0, -1.0),\n"
"    vec2(-1.0,  1.0),\n"
"    vec2( 1.0,  1.0),\n"
"    vec2(-1.0, -1.0),\n"
"    vec2( 1.0,  1.0),\n"
"    vec2( 1.0, -1.0)\n"
");\n"
"const vec2 uvs[6] = vec2[](\n"
"    vec2(0.0, 1.0),\n"
"    vec2(0.0, 0.0),\n"
"    vec2(1.0, 0.0),\n"
"    vec2(0.0, 1.0),\n"
"    vec2(1.0, 0.0),\n"
"    vec2(1.0, 1.0)\n"
");\n"
"void main() {\n"
"    gl_Position = vec4(positions[gl_VertexIndex], 0.0, 1.0);\n"
"    outUV = uvs[gl_VertexIndex];\n"
"}\n";

const char* psShader_MainMenuFragment = ""
"#version 450\n"
"#pragma shader_stage(fragment)\n"
"layout(location = 0) in vec2 inUV;\n"
"layout(location = 0) out vec4 outColor;\n"
"\n"
"layout(set = 0, binding = 0) uniform sampler2D backgroundTexture;\n"
"layout(set = 0, binding = 1) uniform sampler2D newGameButtonTexture;\n"
"layout(set = 0, binding = 2) uniform sampler2D continueButtonTexture;\n"
"layout(set = 0, binding = 3) uniform sampler2D optionsButtonTexture;\n"
"layout(set = 0, binding = 4) uniform sampler2D exitButtonTexture;\n"
"\n"
PS_SHADER_MAIN_MENU_PUSH_CONSTANTS
"\n"
"const float buttonHeightUV = 0.1;\n"
"const float buttonCenterYStart = 0.55;\n"
"const float buttonSpacingY = 0.12;\n"
"const float buttonCenterX = 0.5;\n"
"\n"
"vec4 sampleButton(vec2 uv, vec2 center, vec2 size, sampler2D tex) {\n"
"    vec2 halfSize = size * 0.5;\n"
"    vec2 minBound = center - halfSize;\n"
"    vec2 maxBound = center + halfSize;\n"
"\n"
"    if (uv.x >= minBound.x && uv.x <= maxBound.x && uv.y >= minBound.y && uv.y <= maxBound.y) {\n"
"        vec2 buttonUV = (uv - minBound) / size;\n"
"        return texture(tex, buttonUV);\n"
"    }\n"
"    return vec4(0.0);\n"
"}\n"
"\n"
"void main() {\n"
"    vec2 flippedUV = vec2(inUV.x, 1.0 - inUV.y);\n"
"\n"
"    float screenAspect = pushConstants.data.windowWidth / pushConstants.data.windowHeight;\n"
"    float targetAspect = pushConstants.data.backgroundImageWidth / pushConstants.data.backgroundImageHeight;\n"
"    vec2 scale = vec2(1.0, 1.0);\n"
"    vec2 offset = vec2(0.0, 0.0);\n"
"\n"
"    if (screenAspect > targetAspect) {\n"
"        scale.x = targetAspect / screenAspect;\n"
"        offset.x = (1.0 - scale.x) * 0.5;\n"
"    } else {\n"
"        scale.y = screenAspect / targetAspect;\n"
"        offset.y = (1.0 - scale.y) * 0.5;\n"
"    }\n"
"\n"
"    vec2 backgroundUV = (flippedUV - offset) / scale;\n"
"    vec4 bgColor = vec4(0.0, 0.0, 0.0, 0.0);\n"
"    if (backgroundUV.x >= 0.0 && backgroundUV.x <= 1.0 && backgroundUV.y >= 0.0 && backgroundUV.y <= 1.0) {\n"
"        bgColor = texture(backgroundTexture, backgroundUV);\n"
"    }\n"
"\n"
"    vec4 finalColor = bgColor;\n"
"\n"
"    float buttonImageAspect = pushConstants.data.buttonImageWidth / pushConstants.data.buttonImageHeight;\n"
"    float buttonWidthUV = buttonHeightUV * buttonImageAspect * (pushConstants.data.windowHeight / pushConstants.data.windowWidth);\n"
"    vec2 correctedButtonSize = vec2(buttonWidthUV, buttonHeightUV);\n"
"\n"
"    vec2 buttonPositions[4];\n"
"    buttonPositions[0] = vec2(buttonCenterX, buttonCenterYStart + buttonSpacingY * 0.0);\n"
"    buttonPositions[1] = vec2(buttonCenterX, buttonCenterYStart + buttonSpacingY * 1.0);\n"
"    buttonPositions[2] = vec2(buttonCenterX, buttonCenterYStart + buttonSpacingY * 2.0);\n"
"    buttonPositions[3] = vec2(buttonCenterX, buttonCenterYStart + buttonSpacingY * 3.0);\n"
"\n"
"    vec4 btnColor = vec4(0.0);\n"
"\n"
"    btnColor = sampleButton(flippedUV, buttonPositions[0], correctedButtonSize, newGameButtonTexture);\n"
"    if (btnColor.a > 0.0) {\n"
"        finalColor = mix(finalColor, btnColor, btnColor.a);\n"
"    }\n"
"\n"
"    btnColor = sampleButton(flippedUV, buttonPositions[1], correctedButtonSize, continueButtonTexture);\n"
"    if (btnColor.a > 0.0) {\n"
"        finalColor = mix(finalColor, btnColor, btnColor.a);\n"
"    }\n"
"\n"
"    btnColor = sampleButton(flippedUV, buttonPositions[2], correctedButtonSize, optionsButtonTexture);\n"
"    if (btnColor.a > 0.0) {\n"
"        finalColor = mix(finalColor, btnColor, btnColor.a);\n"
"    }\n"
"\n"
"    btnColor = sampleButton(flippedUV, buttonPositions[3], correctedButtonSize, exitButtonTexture);\n"
"    if (btnColor.a > 0.0) {\n"
"        finalColor = mix(finalColor, btnColor, btnColor.a);\n"
"    }\n"
"\n"
"    outColor = finalColor;\n"
"}\n";
