#include "ps_shader.h"

const char* psShader_PresentationVertex = ""
"\n"
"#version 450\n"
"\n"
"#pragma shader_stage(vertex)\n"
"\n"
"layout (location = 0) out vec2 outUV;\n"
"\n"
"layout (push_constant) uniform PushConstants {\n"
"    float windowWidth;\n"
"    float windowHeight;\n"
"    float framebufferWidth;\n"
"    float framebufferHeight;\n"
"} pushConstants;\n"
"\n"
"const vec2 positions[6] = vec2[](\n"
"    vec2(0.0, 0.0),\n"
"    vec2(0.0, 1.0),\n"
"    vec2(1.0, 1.0),\n"
"    vec2(0.0, 0.0),\n"
"    vec2(1.0, 1.0),\n"
"    vec2(1.0, 0.0)\n"
");\n"
"\n"
"void main() {\n"
"    vec2 pos = positions[gl_VertexIndex];\n"
"\n"
"    outUV = pos;\n"
"\n"
"    pos = pos * 2.0 - 1.0;\n"
"\n"
"    float windowAspect = pushConstants.windowWidth / pushConstants.windowHeight;\n"
"    float framebufferAspect = pushConstants.framebufferWidth / pushConstants.framebufferHeight;\n"
"    if (windowAspect > framebufferAspect) {\n"
"        pos.x *= framebufferAspect / windowAspect;\n"
"    } else {\n"
"        pos.y *= windowAspect / framebufferAspect;\n"
"    }\n"
"    gl_Position = vec4(pos, 0.0, 1.0);\n"
"\n"
"}\n";

const char* psShader_PresentationFragment = ""
"#version 450\n"
"\n"
"#pragma shader_stage(fragment)\n"
"\n"
"layout (binding = 0) uniform sampler2D sceneFramebuffer;\n"
"\n"
"layout (location = 0) in vec2 inUV;\n"
"\n"
"layout (location = 0) out vec4 outColor;\n"
"\n"
"void main() \n"
"{\n"
"    outColor = texture(sceneFramebuffer, inUV);\n"
"}\n";
